### PR TITLE
Updated authors file

### PR DESCRIPTION
**Pull request by chigby**
I made the authors file into a markdown document and listed out all of the contributors (that I could find).

### CODE REVIEW

**Comment by melinath** [comment]
I would be inclined to maybe just remove this file. Github's contributor view makes this sort of obsolete.
If we are going to keep the file updated, though, it should just be a list of names. Keeping track of what people contributed could easily get out of hand.

**Comment by harrislapiroff** [comment]
I actually don't think it getting out of hand is too much of an issue. I think an authors file is pretty nice. It's like the credits on a movie. For reference, this is Django's. https://github.com/django/django/blob/master/AUTHORS

**Comment by melinath** [comment]
@harrislapiroff right, and they only list the names, which I think is fine. It's listing what exactly each person contributed that I really have a problem with.

**Comment by harrislapiroff** [comment]
Ohhhhhhhhh. Yeah, that might be tricky to maintain in the future.

**Comment by chigby** [comment]
I'm fine with removing that.

**Comment by chigby** [comment]
@harrislapiroff @melinath this more what you had in mind?

**Comment by melinath** [comment]
@chigby yep, looks good. (Someday we might want to move the note about issuing a PR with your name up to the top, but I think it's okay for now because the list is so short.)

**Pull request merged**
