### PR TITLE
Django 1.8

### PR DESCRIPTION
**Pull request by melinath**
This PR adds tests for Django 1.8 support (and removes official support for 1.6) as well as adding tests for postgres support and adding a flake8 run.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
This looks fairly good, but I wasn't able to use it with a project, since usually I would test on Dancerfly, but it's not 1.8-ready yet. Thoughts?

**Comment by melinath** [comment]
Dancerfly just merged 1.8 support. See littleweaver/django-brambling#778

**Comment by chigby** [comment]
screen shot 2016-04-12 at 16 11 43

**Comment by chigby** [comment]
This seems great to me. I can merge if you want, but I'm not sure what the procedure is for issuing a release.

**Comment by melinath** [comment]
@chigby merge into master and then tell me to cut a release. :-)

**Pull request merged**
